// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://webwrcdshwiuddvkjher.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYndyY2RzaHdpdWRkdmtqaGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTExOTAsImV4cCI6MjA3MDMyNzE5MH0.P6oUtTTw51WmFPVDFWGXJvlCW7GV0qLQlPd_aoKK67Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});